// Solicitudes de compradores - mercado invertido BuySeek
const BUYER_REQUESTS = [
    // ===== AUTOS =====
    {
        id: 'auto-1',
        category: 'autos',
        featured: true,
        title: 'Busco Ferrari 488 GTB 2019+',
        image: 'images/ferrari-488.jpg',
        budget: 240000,
        requirements: 'Color rosso corsa, coupé, impecable estado, documentación completa, menos de 15.000 km.',
        location: 'Miami, FL',
        posted: 'hace 1 día',
        negotiable: true,
        views: 48,
        offers: 5,
        buyer: { id: 'b1', name: 'Carlos M.', rating: 4.9, reviews: 18 }
    },
    {
        id: 'auto-2',
        category: 'autos',
        featured: true,
        title: 'Busco Porsche 911 Carrera Negro',
        image: 'images/porsche-carrera.jpg',
        budget: 180000,
        requirements: 'Modelo reciente, interior negro o gris, llantas deportivas, paquete premium.',
        location: 'Miami, FL',
        posted: 'hace 1 día',
        negotiable: true,
        views: 56,
        offers: 7,
        buyer: { id: 'b2', name: 'Sarah K.', rating: 4.7, reviews: 24 }
    },
    {
        id: 'auto-3',
        category: 'autos',
        featured: false,
        title: 'Busco Porsche 911 GT3 Azul',
        image: 'images/porsche-gt3.jpg',
        budget: 195000,
        requirements: 'Miami Blue o similar, alerón trasero, escape deportivo, estado impecable.',
        location: 'Los Ángeles, CA',
        posted: 'hace 3 días',
        negotiable: false,
        views: 38,
        offers: 5,
        buyer: { id: 'b3', name: 'James L.', rating: 4.5, reviews: 9 }
    },
    {
        id: 'auto-4',
        category: 'autos',
        featured: false,
        title: 'Busco BMW Serie 3 2019+',
        image: 'images/bmw-serie3.jpg',
        budget: 45000,
        requirements: 'Automático, menos de 60.000 km, service al día, color oscuro preferido.',
        location: 'Buenos Aires',
        posted: 'hace 2 días',
        negotiable: true,
        views: 31,
        offers: 4,
        buyer: { id: 'b4', name: 'María G.', rating: 4.8, reviews: 15 }
    },
    {
        id: 'auto-5',
        category: 'autos',
        featured: false,
        title: 'Busco Tesla Model S Plaid',
        image: 'images/tesla-models.jpg',
        budget: 95000,
        requirements: 'Versión Plaid o Long Range, autopilot, batería en buen estado.',
        location: 'Nueva York, NY',
        posted: 'hace 4 días',
        negotiable: true,
        views: 42,
        offers: 6,
        buyer: { id: 'b5', name: 'David R.', rating: 4.6, reviews: 11 }
    },
    {
        id: 'auto-6',
        category: 'autos',
        featured: false,
        title: 'Busco Ford Mustang GT 2021',
        image: 'images/ford-mustang.jpg',
        budget: 42000,
        requirements: 'V8, automático, pocos kilómetros, color rojo o negro.',
        location: 'Chicago, IL',
        posted: 'hace 5 días',
        negotiable: true,
        views: 27,
        offers: 3,
        buyer: { id: 'b6', name: 'Ana P.', rating: 5.0, reviews: 7 }
    },

    // ===== INMUEBLES =====
    {
        id: 'inm-1',
        category: 'inmobiliaria',
        operation: 'compra',
        featured: true,
        title: 'Busco Apartamento en Miami Beach',
        image: 'images/apt-miami-beach.jpg',
        budget: 850000,
        requirements: '2-3 dormitorios, vista al mar, mínimo 120m², área de piscina, estacionamiento.',
        location: 'Miami Beach, FL',
        posted: 'hace 1 día',
        negotiable: true,
        views: 62,
        offers: 8,
        buyer: { id: 'b7', name: 'Roberto F.', rating: 4.8, reviews: 20 }
    },
    {
        id: 'inm-2',
        category: 'inmobiliaria',
        operation: 'compra',
        featured: true,
        title: 'Busco Loft en Manhattan',
        image: 'images/loft-manhattan.jpg',
        budget: 1200000,
        requirements: 'Estilo industrial, techos altos, 2 ambientes, cerca del metro, luminoso.',
        location: 'Nueva York, NY',
        posted: 'hace 2 días',
        negotiable: false,
        views: 45,
        offers: 4,
        buyer: { id: 'b8', name: 'Elena V.', rating: 4.9, reviews: 16 }
    },
    {
        id: 'inm-3',
        category: 'inmobiliaria',
        operation: 'compra',
        featured: false,
        title: 'Busco Casa Minimalista en Weston',
        image: 'images/casa-moderna.jpg',
        budget: 1850000,
        requirements: '4 dormitorios, jardín amplio, piscina, diseño minimalista, tonos neutros.',
        location: 'Weston, FL',
        posted: 'hace 4 días',
        negotiable: false,
        views: 41,
        offers: 6,
        buyer: { id: 'b9', name: 'Patricia H.', rating: 4.4, reviews: 8 }
    },
    {
        id: 'inm-4',
        category: 'inmobiliaria',
        operation: 'compra',
        featured: true,
        title: 'Busco Penthouse en Sunny Isles',
        image: 'images/penthouse-ocean.jpg',
        budget: 2200000,
        requirements: '3 habitaciones, vista directa al océano, balcón amplio, pisos altos, 150m²+.',
        location: 'Sunny Isles, FL',
        posted: 'hace 2 días',
        negotiable: true,
        views: 52,
        offers: 4,
        buyer: { id: 'b10', name: 'Michael T.', rating: 4.7, reviews: 22 }
    },
    {
        id: 'inm-5',
        category: 'inmobiliaria',
        operation: 'alquiler',
        featured: false,
        title: 'Alquilo Apartamento en Brickell',
        image: 'images/apt-brickell.jpg',
        budget: 8000,
        budgetPeriod: '/mes',
        requirements: '2-3 dormitorios, amueblado, vista al mar, gimnasio y piscina en edificio.',
        location: 'Brickell, Miami, FL',
        posted: 'hace 2 días',
        negotiable: true,
        views: 33,
        offers: 4,
        buyer: { id: 'b11', name: 'Laura S.', rating: 4.6, reviews: 13 }
    },
    {
        id: 'inm-6',
        category: 'inmobiliaria',
        operation: 'compra',
        featured: false,
        title: 'Busco Departamento en Palermo',
        image: 'images/dept-palermo.jpg',
        budget: 320000,
        requirements: '2 ambientes, balcón, luminoso, edificio con amenities, zona segura.',
        location: 'Palermo, Buenos Aires',
        posted: 'hace 6 días',
        negotiable: true,
        views: 28,
        offers: 5,
        buyer: { id: 'b12', name: 'Fernando D.', rating: 4.5, reviews: 10 }
    }
];

// Vendedores verificados
const SAMPLE_SELLERS = [
    { id: 's1', name: 'Luxury Motors Miami', rating: 4.9, reviews: 156, deals: 89, type: 'Concesionaria', location: 'Miami, FL' },
    { id: 's2', name: 'Elite Auto Group', rating: 4.7, reviews: 89, deals: 52, type: 'Concesionaria', location: 'Los Ángeles, CA' },
    { id: 's3', name: 'Coastal Realty', rating: 4.8, reviews: 203, deals: 134, type: 'Inmobiliaria', location: 'Miami Beach, FL' },
    { id: 's4', name: 'Premium Estates NY', rating: 4.6, reviews: 67, deals: 41, type: 'Inmobiliaria', location: 'Nueva York, NY' }
];
